### ISSUE TITLE
BUG - WMDB scan module not working

### ISSUE THREAD

**Issue by yellow-starburst** [byt3bl33d3r/WitnessMe#11]
Probably a simple installation that I need to run
Command:
`WMDB ≫ scan 1`

Output:
```
Traceback (most recent call last):
  File "./wmdb.py", line 239, in cmdloop
    await self.scan()
  File "./wmdb.py", line 197, in scan
    self.signatures.load()
  File "/home/WitnessMe/witnessme/signatures.py", line 15, in load
    self.signatures.append(yaml.load(sig, Loader=yaml.CLoader))
AttributeError: module 'yaml' has no attribute 'CLoader'
Error calling command 'scan': module 'yaml' has no attribute 'CLoader'
```

**Comment by yellow-starburst** [comment]
Probably a simple installation that I need to run:
https://github.com/yaml/pyyaml/issues/108

**Comment by byt3bl33d3r** [comment]
This should be fixed now. Thanks
