### ISSUE TITLE
Error taking screenshot: expected string or bytes-like object

### ISSUE THREAD

**Issue by faun88** [byt3bl33d3r/WitnessMe#6]
I'll started WitnessMe with a .nessus file, but I receive the error 

`Error taking screenshot: expected string or bytes-like object`

Screenshot: https://monosnap.com/file/OofiFk9CJ4JSLOr8dJX17x8rFon9kY

**Comment by faun88** [comment]
Note: same issue with text file with a list of IP's.

**Comment by faun88** [comment]
Other example:

`python witnessme.py google.com

[I:pyppeteer.launcher] Browser listening on: ws://127.0.0.1:49937/devtools/browser/3cbd14a4-52b2-4e37-a0ea-e5791a7b5ae5
2019-11-12 16:54:38,022 [INFO] - witnessme.py: start_scan - Using 25 worker thread(s)
2019-11-12 16:54:38,991 [ERROR] - witnessme.py: worker - Error taking screenshot: net::ERR_EMPTY_RESPONSE at http://google.com:443
2019-11-12 16:54:39,004 [ERROR] - witnessme.py: worker - Error taking screenshot: net::ERR_SSL_PROTOCOL_ERROR at https://google.com:80
2019-11-12 16:54:40,171 [ERROR] - witnessme.py: worker - Error taking screenshot: expected string or bytes-like object
2019-11-12 16:54:40,181 [ERROR] - witnessme.py: worker - Error taking screenshot: expected string or bytes-like object
2019-11-12 16:54:42,682 [INFO] - witnessme.py: task_watch - total: 8, done: 4, pending: 4
2019-11-12 16:54:47,683 [INFO] - witnessme.py: task_watch - total: 8, done: 4, pending: 4
2019-11-12 16:54:52,683 [INFO] - witnessme.py: task_watch - total: 8, done: 4, pending: 4
2019-11-12 16:54:57,688 [INFO] - witnessme.py: task_watch - total: 8, done: 4, pending: 4
2019-11-12 16:55:02,693 [INFO] - witnessme.py: task_watch - total: 8, done: 4, pending: 4
2019-11-12 16:55:07,695 [INFO] - witnessme.py: task_watch - total: 8, done: 4, pending: 4
2019-11-12 16:55:12,700 [INFO] - witnessme.py: task_watch - total: 8, done: 4, pending: 4
2019-11-12 16:55:13,391 [INFO] - witnessme.py: worker - Task for url http://google.com:8080 timed out
2019-11-12 16:55:13,391 [INFO] - witnessme.py: worker - Task for url https://google.com:8080 timed out
2019-11-12 16:55:13,394 [INFO] - witnessme.py: worker - Task for url https://google.com:8443 timed out
2019-11-12 16:55:13,394 [INFO] - witnessme.py: worker - Task for url http://google.com:8443 timed out
[I:pyppeteer.launcher] terminate chrome process...`

**Comment by byt3bl33d3r** [comment]
You're using python 3 right? What OS are you running on ?

**Comment by faun88** [comment]
> You're using python 3 right? What OS are you running on ?

Hi, yes python3. I’ve tried both MacOS and Ubuntu (latest) in a Docker container. Both gave same issue.

**Comment by byt3bl33d3r** [comment]
The only thing I can think of is try installing it outside of a docker container and see if it works there?

**Comment by faun88** [comment]
> The only thing I can think of is try installing it outside of a docker container and see if it works there?

MacOs was not in a docker container, only Ubuntu was.

**Comment by byt3bl33d3r** [comment]
No clue. Works for me:
![image](https://user-images.githubusercontent.com/5151193/68712455-ff7f1180-0558-11ea-8f84-a3e4be22d870.png)

Can you share the text file you're using?

**Comment by faun88** [comment]
Hi,

Unfortunately I'm not allowed to share, but it's just a bunch of public ip adresses.

Even with google.com it doesn't work for me:

<img width="1258" alt="afbeelding" src="https://user-images.githubusercontent.com/4800291/68712988-1fd0bf80-059d-11ea-9933-af639e1423d2.png">

**Comment by faun88** [comment]
Unfortunately I'm not allowed to share our public ip adresses, but it's just a bunch of public ip adresses.

It didn't work for google.com as in your example as well:

<img width="1037" alt="witnessme2" src="https://user-images.githubusercontent.com/4800291/68713188-953c9000-059d-11ea-9241-de6d96410d9b.png">

Anyway, thank you very much for your help and the efforts in building this tool.

**Comment by byt3bl33d3r** [comment]
@faun88 something that might help me figure this out.

Can you put the following right above [line 120](https://github.com/byt3bl33d3r/WitnessMe/blob/master/witnessme.py#L120):
```python
import traceback; traceback.print_exc()
```
Run it again and give me the traceback?

Thanks

**Comment by faun88** [comment]
> @faun88 something that might help me figure this out.
> 
> Can you put the following right above [line 120](https://github.com/byt3bl33d3r/WitnessMe/blob/master/witnessme.py#L120):
> 
> ```python
> import traceback; traceback.print_exc()
> ```
> 
> Run it again and give me the traceback?
> 
> Thanks

Sure:

```
python witnessme.py www.google.com

[I:pyppeteer.launcher] Browser listening on: ws://127.0.0.1:50659/devtools/browser/40c461a1-4dd3-43e7-b09c-2bf0c008abf5
2019-11-12 22:52:31,551 [INFO] - witnessme.py: start_scan - Using 25 worker thread(s)
Traceback (most recent call last):
  File "witnessme.py", line 112, in worker
    r = await asyncio.wait_for(screenshot(url, page), timeout=args.timeout)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "witnessme.py", line 59, in screenshot
    "waitUntil": "networkidle0"
  File "/Users/dennis/.local/share/virtualenvs/WitnessMe-lSv3YZHu/src/pyppeteer-dev/pyppeteer/page.py", line 881, in goto
    raise PageError(result)
pyppeteer.errors.PageError: net::ERR_SSL_PROTOCOL_ERROR at https://www.google.com:80
2019-11-12 22:52:32,598 [ERROR] - witnessme.py: worker - Error taking screenshot: net::ERR_SSL_PROTOCOL_ERROR at https://www.google.com:80
Traceback (most recent call last):
  File "witnessme.py", line 112, in worker
    r = await asyncio.wait_for(screenshot(url, page), timeout=args.timeout)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "witnessme.py", line 59, in screenshot
    "waitUntil": "networkidle0"
  File "/Users/dennis/.local/share/virtualenvs/WitnessMe-lSv3YZHu/src/pyppeteer-dev/pyppeteer/page.py", line 881, in goto
    raise PageError(result)
pyppeteer.errors.PageError: net::ERR_CONNECTION_RESET at http://www.google.com:443
2019-11-12 22:52:32,600 [ERROR] - witnessme.py: worker - Error taking screenshot: net::ERR_CONNECTION_RESET at http://www.google.com:443
Traceback (most recent call last):
  File "witnessme.py", line 112, in worker
    r = await asyncio.wait_for(screenshot(url, page), timeout=args.timeout)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "witnessme.py", line 77, in screenshot
    'fullPage': True
  File "/Users/dennis/.local/share/virtualenvs/WitnessMe-lSv3YZHu/src/pyppeteer-dev/pyppeteer/page.py", line 1245, in screenshot
    mimeType, _ = mimetypes.guess_type(options['path'])
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/mimetypes.py", line 291, in guess_type
    return _db.guess_type(url, strict)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/mimetypes.py", line 116, in guess_type
    scheme, url = urllib.parse.splittype(url)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/parse.py", line 983, in splittype
    match = _typeprog.match(url)
TypeError: expected string or bytes-like object
2019-11-12 22:52:34,420 [ERROR] - witnessme.py: worker - Error taking screenshot: expected string or bytes-like object
Traceback (most recent call last):
  File "witnessme.py", line 112, in worker
    r = await asyncio.wait_for(screenshot(url, page), timeout=args.timeout)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "witnessme.py", line 77, in screenshot
    'fullPage': True
  File "/Users/dennis/.local/share/virtualenvs/WitnessMe-lSv3YZHu/src/pyppeteer-dev/pyppeteer/page.py", line 1245, in screenshot
    mimeType, _ = mimetypes.guess_type(options['path'])
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/mimetypes.py", line 291, in guess_type
    return _db.guess_type(url, strict)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/mimetypes.py", line 116, in guess_type
    scheme, url = urllib.parse.splittype(url)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/parse.py", line 983, in splittype
    match = _typeprog.match(url)
TypeError: expected string or bytes-like object
2019-11-12 22:52:35,376 [ERROR] - witnessme.py: worker - Error taking screenshot: expected string or bytes-like object
2019-11-12 22:52:36,221 [INFO] - witnessme.py: task_watch - total: 8, done: 4, pending: 4
2019-11-12 22:52:41,221 [INFO] - witnessme.py: task_watch - total: 8, done: 4, pending: 4
2019-11-12 22:52:46,222 [INFO] - witnessme.py: task_watch - total: 8, done: 4, pending: 4
2019-11-12 22:52:51,227 [INFO] - witnessme.py: task_watch - total: 8, done: 4, pending: 4
2019-11-12 22:52:56,230 [INFO] - witnessme.py: task_watch - total: 8, done: 4, pending: 4
2019-11-12 22:53:01,230 [INFO] - witnessme.py: task_watch - total: 8, done: 4, pending: 4
```

**Comment by byt3bl33d3r** [comment]
Hmmmm, try replacing line 72 [here](https://github.com/byt3bl33d3r/WitnessMe/blob/master/witnessme.py#L72) with this:
```python
screenshot_path = str(pathlib.Path(f'./{report_folder}/{screenshot}').absolute())
```

**Comment by faun88** [comment]
That worked! Many thanks!

**Comment by byt3bl33d3r** [comment]
Awesome. That's actually good to know. It seems that Python interprets `pathlib` objects differently between Python v3.7.4 and Python >= 3.7.5. I'll commit this change tonight.

**Comment by faun88** [comment]
> Awesome. That's actually good to know. It seems that Python interprets `pathlib` objects differently between Python v3.7.4 and Python >= 3.7.5. I'll commit this change tonight.

Many thanks! Glas that the issue was informative for you.
